name: 脚本运行问题报告 ( Script Bug Report )
description: 脚本运行问题.
title: "[Script Bug]: "
labels: ["问题修复", "脚本运行问题"]
assignees:
  - pur1fying
body:
  - type: checkboxes
    id: script_version
    attributes:
      label: BAAS版本是否为最新
      description: 在报告问题前,请检查BAAS版本是否更新到最新, [查询方式](https://baas.wiki/usage_doc/update.html#%E5%A6%82%E4%BD%95%E6%9F%A5%E8%AF%A2%E5%BD%93%E5%89%8D%E7%89%88%E6%9C%AC)
      options:
        - label: 是, 我已经确认BAAS版本为最新
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 请根据提示提交相关材料

  - type: textarea
    id: bug_description
    attributes:
      label: 错误描述 ( Bug Description )
      description: 你提供的信息越详细, 越能帮助我们快速定位问题
      value: "## 错误描述 \n (请在这里填写错误的文字描述, 包括你的操作, 是否能稳定复现) \n\n ## 报错日志 / 录屏 / 模拟器720p截图 "

    validations:
      required: true

