name: 启动器问题报告 ( Installer Bug Report )
description: 无法启动BAAS的GUI界面.
title: "[Installer Bug]: "
labels: ["问题修复", "GUI相关", "启动器问题"]
assignees:
  - Kiramei,pur1fying
body:
  - type: dropdown
    id: version
    attributes:
      label: 启动器版本( Version )
      description: BAAS启动器的版本
      options:
        - 1.4.3 (Latest)
        - 1.4.2
        - 1.4.1
        - 1.4.0
        - 1.3.0.1 Beta
        - 1.3.0
        - 1.2.0
        - 1.1.3
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.0 Beta
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 请根据提示提交相关材料

  - type: textarea
    id: bug_description
    attributes:
      label: 错误描述 ( Bug Description )
      description: 你提供的信息越详细, 越能帮助我们快速定位问题
      value: "## 错误描述 \n (请在这里填写错误的文字描述, 包括你的系统信息, 操作, 是否能稳定复现) \n\n ## 报错截图 / 录屏 \n\n ## 如果你的BAAS版本高于1.4.0, 请提交setup.toml "

    validations:
      required: true

